spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:15495/shop_db
    username: root
    password: '0000'

  decorator:
    datasource:
      p6spy:
        enable-logging: true


Loggin:
  level:
    org.hibernate.SQL: debug


springdoc:
  swagger-ui:
    path: /
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
